apiVersion: v1
kind: pod
metadata:
  name: dodo
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80


          git config --global user.email "dodonotdos@gmail.com"

            git config --global user.name "dodonotdos"