---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fourtimes-po
  namespace: fourtimes
  labels:
    group: two
    project: facebook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-server
  template:
    metadata:
      name: fourtimes-po
      labels:
        app: httpd-server
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
             - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fourtimes-po
  namespace: fourtimes
  labels:
    group: two
    project: facebook
spec:
  type: ClusterIP
  selector:
    app: httpd-server
  ports:
  - port: 80
